### ISSUE TITLE
[automatic-releases] Error: Unexpected token y in JSON at position 0

### ISSUE THREAD

**Issue by sigmasoldi3r** [marvinpinto/actions#138]
From the automatic-releases action https://github.com/marvinpinto/action-automatic-releases

I'm giving a try to the action with the following parameters:
```yml
    - name: Create the snapshot release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN  }}
        title: Snapshot ${{ env.SNAPSHOT_TAG }} build
        prerelease: yes
        automatic_release_tag: ${{ env.SNAPSHOT_TAG }}
```

But it ends with error:
```
2021-04-20T10:26:38.7214793Z ##[group]Run marvinpinto/action-automatic-releases@latest
2021-04-20T10:26:38.7215489Z with:
2021-04-20T10:26:38.7216971Z   repo_token: ***
2021-04-20T10:26:38.7217437Z   title: Snapshot 21w16a build 
2021-04-20T10:26:38.7217926Z   prerelease: yes
2021-04-20T10:26:38.7218409Z   automatic_release_tag: 21w16a
2021-04-20T10:26:38.7218870Z   draft: false
2021-04-20T10:26:38.7219228Z env:
2021-04-20T10:26:38.7219829Z   BUILD_TYPE: Release
2021-04-20T10:26:38.7220408Z   SNAPSHOT_TAG: 21w16a
2021-04-20T10:26:38.7220837Z ##[endgroup]
2021-04-20T10:26:38.8259101Z ##[error]Unexpected token y in JSON at position 0
2021-04-20T10:26:38.8284275Z (node:6279) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token y in JSON at position 0
2021-04-20T10:26:38.8285297Z     at JSON.parse (<anonymous>)
2021-04-20T10:26:38.8286812Z     at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:213282
2021-04-20T10:26:38.8288225Z     at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:213461
2021-04-20T10:26:38.8289509Z     at Generator.next (<anonymous>)
2021-04-20T10:26:38.8290635Z     at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:211750
2021-04-20T10:26:38.8291442Z     at new Promise (<anonymous>)
2021-04-20T10:26:38.8292527Z     at s (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:211495)
2021-04-20T10:26:38.8293972Z     at Object.t.main (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:213025)
2021-04-20T10:26:38.8295504Z     at Object.<anonymous> (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:210868)
2021-04-20T10:26:38.8296933Z     at r (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:124)
2021-04-20T10:26:38.8300892Z (node:6279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2021-04-20T10:26:38.8303749Z (node:6279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-04-20T10:26:38.8386579Z Post job cleanup.
```

**Comment by marvinpinto** [comment]
Hey there, try using `true` instead of `yes` for the prerelease parameter. It is supposed to be a boolean parameter and I suspect that error is because it's trying to coerce "yes" into a bool.  

Reopen this issue if you're still running into the same issue :+1:

**Comment by sigmasoldi3r** [comment]
My bad, I don't know why, but I thought that YAML did translate yes and no to true and false. (The syntax highlight also may be tricking me by coloring yes and no as true or false) 
I'll give it a try later!
