### ISSUE TITLE
automatic_release_tag appears to be required

### ISSUE THREAD

**Issue by 404meemr** [marvinpinto/actions#32]
I honestly just want to bump my version from the previous release, however every time I use this action, I keep getting the same error message:
```
##[error]The parameter "automatic_release_tag" was not set and this does not appear to be a GitHub tag event. (Event: refs/heads/master)
  (node:3970) UnhandledPromiseRejectionWarning: Error: The parameter "automatic_release_tag" was not set and this does not appear to be a GitHub tag event. (Event: refs/heads/master)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:224244
      at Generator.next (<anonymous>)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:221786
      at new Promise (<anonymous>)
      at n (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:221531)
      at Object.t.main (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:223199)
      at Object.<anonymous> (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:221441)
      at r (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:124)
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:923
      at Object.<anonymous> (/home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:933)
  (node:3970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:3970) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit
```

The README shows that I don't need automatic_release_tag, but when I omit it or set it to `null`, I get that error.

Here is my full build file: https://pastebin.com/yaA3iFWj

**Comment by marvinpinto** [comment]
Yeah you need to either supply the tag yourself (via pushing a tag) or use the `automatic_release_tag`.

From your build output above it looks like you were trying to execute the action on a non-tag event (like a push, or a pull request).

Reopen if you still feel this is a bug :+1:

**Comment by elendil-software** [comment]
Hi,

I have the same problem.

What do you mean by "supply the tag yourself (via pushing a tag)" ?

I'm creating a tag with this action : https://github.com/marketplace/actions/create-tag 
Shouldn't this work ?
