### ISSUE TITLE
one package's failure to publish artifacts

### ISSUE THREAD

**Issue by drcandacemakedamoore** [marvinpinto/actions#493]
I use this package on several of my own, and it usually works. On one single package (https://github.com/eegyolk-ai/eegyolk/) I fail to publish artifacts. The error message is very confusing:  Creating new release
  Error: Not Found
  (node:1692) UnhandledPromiseRejectionWarning: HttpError: Not Found
      at /home/runner/work/_actions/marvinpinto/action-automatic-releases/latest/dist/index.js:1:361954
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  (node:1692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:1692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have found that even including some code on permissions in my on-tag.yml does not work, and I get the same error. Is there anything else I should attempt. I report it as an issue, because maybe the error could be made to fail in a more readable way?

**Comment by drcandacemakedamoore** [comment]
It seems to be the exact same issue as #340 but it did not resolve

**Comment by drcandacemakedamoore** [comment]
It actually resolved with creating a different token. I can not be 100% sure why, but it seems to be a Github bug.
