### ISSUE TITLE
How to upload binary/ executable after tag is released.

### ISSUE THREAD

**Issue by wxguy** [marvinpinto/actions#520]
Right now I am using two action files to create a binary for Linux and Windows. The time taken to build Windows is a little longer than Linux. Therefore, the Linux action file creates a release tag and uploads the binary before Windows could complete it. 

The issue here I am facing is windows release fails with the following error:

```
Creating new release
  Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
  (node:3964) UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
      at D:\a\_actions\marvinpinto\action-automatic-releases\latest\dist\index.js:1:361954
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  (node:3964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:3964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is there a way to release both the files (Windows and Linux) which are generated on different VM at the same time? Or is it possible to append the tag for uploading a new binary?

**Comment by ldeluigi** [comment]
Use a single workflow, with a linux job and a windows job. When both are done, run the release job that collects both artifacts (binaries) and releases them altogether
