### ISSUE TITLE
action-automatic-releases: set-output deprecated

### ISSUE THREAD

**Issue by AlexAtkinson** [marvinpinto/actions#695]
When using  `"marvinpinto/action-automatic-releases@latest"`, the following deprecation warning is issued.

```
Warning: The `set-output` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files. For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by sbe-arg** [comment]
This project is unmaintained atm

**Comment by AndyLeibundgut** [comment]
It appears to be fixed in this marvinpinto/actions repo. The action that mirrors to the marvinpinto/action-automatic-releases repo seems to be broken. Clone down both repos, navigate to the ./packages/automatic-releases folder in the actions repo and run the yarn commands from the workflow. It will create a dist folder under ./packages/automatic-releases. Grab the contents of index.js and copy if over to the corresponding index.js file in action-automatic-releases repo and that seems to do the trick. Host the fixed version of actions-automatic-releases in your own github environment and you should be good to go.

**Comment by mathieucarbou** [comment]
> yarn

```
~/.../packages/automatic-releases ( master → origin S:91 ?:79 ⊘ )
❯  yarn build
yarn run v1.22.19
$ webpack --config webpack.config.js
assets by status 323 bytes [cached] 1 asset
./src/index.ts 39 bytes [built] [code generated] [2 errors]

ERROR in /Users/mat/Data/Workspace/forks/marvinpinto-actions/packages/automatic-releases/tsconfig.json
./src/index.ts /Users/mat/Data/Workspace/forks/marvinpinto-actions/packages/automatic-releases/tsconfig.json
[tsl] ERROR
      TS5083: Cannot read file '/Users/mat/Data/Workspace/forks/marvinpinto-actions/tsconfig.json'.
ts-loader-default_e3b0c44298fc1c14

ERROR in ./src/index.ts
Module build failed (from ../../node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (/Users/mat/Data/Workspace/forks/marvinpinto-actions/node_modules/ts-loader/dist/index.js:18:18)

webpack 5.89.0 compiled with 2 errors in 229 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mathieucarbou** [comment]
> > yarn
> 
> ```
> ~/.../packages/automatic-releases ( master → origin S:91 ?:79 ⊘ )
> ❯  yarn build
> yarn run v1.22.19
> $ webpack --config webpack.config.js
> assets by status 323 bytes [cached] 1 asset
> ./src/index.ts 39 bytes [built] [code generated] [2 errors]
> 
> ERROR in /Users/mat/Data/Workspace/forks/marvinpinto-actions/packages/automatic-releases/tsconfig.json
> ./src/index.ts /Users/mat/Data/Workspace/forks/marvinpinto-actions/packages/automatic-releases/tsconfig.json
> [tsl] ERROR
>       TS5083: Cannot read file '/Users/mat/Data/Workspace/forks/marvinpinto-actions/tsconfig.json'.
> ts-loader-default_e3b0c44298fc1c14
> 
> ERROR in ./src/index.ts
> Module build failed (from ../../node_modules/ts-loader/index.js):
> Error: error while parsing tsconfig.json
>     at Object.loader (/Users/mat/Data/Workspace/forks/marvinpinto-actions/node_modules/ts-loader/dist/index.js:18:18)
> 
> webpack 5.89.0 compiled with 2 errors in 229 ms
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

oh boy, cloning the repo through this remote, a fork, with ssh or http leads to:

```
Cloning into 'actions'...
remote: Enumerating objects: 1786, done.
remote: Counting objects: 100% (433/433), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 1786 (delta 389), reused 343 (delta 343), pack-reused 1353
Receiving objects: 100% (1786/1786), 1.83 MiB | 449.00 KiB/s, done.
Resolving deltas: 100% (1154/1154), done.
git-lfs smudge 'packages/keybase-notifications/images/keybase-gh-notification-example.png': git-lfs: command not found
error: external filter 'git-lfs smudge %f' failed 127
error: external filter 'git-lfs smudge %f' failed
fatal: packages/keybase-notifications/images/keybase-gh-notification-example.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by mathieucarbou** [comment]
I was finally able to create a fork here https://github.com/mathieucarbou/marvinpinto-action-automatic-releases containing the node version update + the set-output fix.

I had to download the zip file of the master branch... git was not able to clone.
